server:
  port: 9086

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AppleDevApp/usdox-spring-cloud
          search-paths: usdox-config
          username:
          password:
      label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 10000
    instance-id: ${spring.application.name}-${eureka.instance.ip-address}-${server.port}-${random.value}
    lease-renewal-interval-in-seconds: 10000
    lease-expiration-duration-in-seconds: 30000