server:
  port: 9086

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
